openapi: 3.0.0
info:
  title: Orders API
  description: Uma API para gerenciar pedidos
  version: 1.0.0

paths:
  /orders:
    get:
      summary: Lista todos os pedidos
      operationId: getOrders
      responses:
        '200':
          description: Lista de pedidos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/definitions/Order'

    post:
      summary: Cria um novo pedido
      operationId: createOrder
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/definitions/Order'
      responses:
        '201':
          description: Pedido criado
          content:
            application/json:
              schema:
                $ref: '#/definitions/Order'

  /orders/{id}:
    get:
      summary: Obtém um pedido específico
      operationId: getOrder
      parameters:
        - name: id
          in: path
          required: true
          description: ID do pedido
          schema:
            type: string
      responses:
        '200':
          description: Pedido encontrado
          content:
            application/json:
              schema:
                $ref: '#/definitions/Order'

    delete:
      summary: Exclui um pedido
      operationId: deleteOrder
      parameters:
        - name: id
          in: path
          required: true
          description: ID do pedido
          schema:
            type: string
      responses:
        '200':
          description: Pedido excluído

definitions:
  Order:
    type: object
    properties:
      id:
        type: string
        description: ID do pedido
      customerId:
        type: string
        description: ID do cliente
      productId:
        type: string
        description: ID do produto
      quantity:
        type: integer
        description: Quantidade do produto
      price:
        type: number
        description: Preço do produto
